### ISSUE TITLE
[BUG]: Error TS2345 started appearing after upgrading from 19.0.6 to 19.0.7(latest)

### ISSUE THREAD

**Issue by aramovic79** [octokit/rest.js#289]
### What happened?

After upgrading @octokit/rest to the latest one, this TS2345 error started appearing: 

_Error TS2345: Argument of type '{ body: string; issue_number: number; owner: string; repo: string; }' is not assignable to parameter of type 'RequestParameters & Omit<{ owner: string; repo: string; issue_number: number; } & **{ data: _never_; }**, "baseUrl" | "headers" | "mediaType">'_

cc: @gr2m, @wolfy1339

### Versions

Node v14.21.1  typescript@4.9.5  @octokit/rest@19.0.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Can you share the version of `@octokit/types` that is installed?

I think this could be related to an issue in that package. https://github.com/octokit/types.ts/issues/528

**Comment by aramovic79** [comment]
> Can you share the version of `@octokit/types` that is installed?
> 
> I think this could be related to an issue in that package. [octokit/types.ts#528](https://github.com/octokit/types.ts/issues/528)

Version is 9.1.2
As you spotted well - the issue is caused by the code here: @octokit/types/dist-types/generated/Endpoints.d.ts:14
What would be your proposal? We've for now downgraded version to the previous one.

**Comment by wolfy1339** [comment]
For now downgrading is the only way to avoid this, until my fix gets landed

**Comment by wolfy1339** [comment]
Closing as octokit/types#528 tracks this already
